# Generated by Django 6.0.4 on 2026-04-19 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_itemtransaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleexpense',
            name='dayofweek',
        ),
        migrations.AddField(
            model_name='scheduleexpense',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_main.account'),
        ),
        migrations.AlterField(
            model_name='scheduleexpense',
            name='type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10),
        ),
    ]
