# Generated by Django 6.0.4 on 2026-04-19 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_itemtransaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_main.account'),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
