# Generated by Django 6.0.4 on 2026-04-19 02:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_merge_20260419_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtransaction',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='app_main.category'),
        ),
        migrations.AlterField(
            model_name='itemtransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
