# Generated by Django 6.0.4 on 2026-04-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_itemtransaction_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtransaction',
            name='date',
            field=models.DateField(),
        ),
    ]
